name: Create Plugin Update

on:
    workflow_dispatch:
    schedule:
        - cron: '0 0 1 * *' # run once a month on the 1st day

permissions:
    contents: write
    pull-requests: write

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 18 # Use the Node.js version compatible with your project

        - name: Install dependencies
          run: npm install

        - name: Build project
          run: npm run build

        - name: Run tests
          run: npm test

        - name: Create Plugin Update
          uses: grafana/plugin-actions/create-plugin-update@main
          # Uncomment and provide necessary inputs if required by the action
          # with:
          #   token: ${{ secrets.GITHUB_TOKEN }}